# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.4.0
#     hooks:
#       # - id: check-added-large-files
#       #   stages: [commit]
#       - id: check-ast
#         stages: [commit]
#       - id: check-case-conflict
#         stages: [commit]
#       - id: check-docstring-first
#         stages: [commit]
#       - id: check-merge-conflict
#         stages: [commit]
#       - id: check-symlinks
#         stages: [commit]
#       - id: check-xml
#         stages: [commit]
#       - id: check-yaml
#         stages: [commit]
#       - id: debug-statements
#         stages: [commit]
#       - id: end-of-file-fixer
#         stages: [commit]
#       - id: mixed-line-ending
#         stages: [commit]
#       - id: trailing-whitespace
#         stages: [commit]
#       - id: fix-byte-order-marker
#         stages: [commit]

  # - repo: https://github.com/psf/black
  #   rev: 22.12.0
  #   hooks:
  #     - id: black
  #       stages: [commit]
  #       args: [".", "--line-length=101"]
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.8.0
  #   hooks:
  #     - id: blacken-docs
  #       stages: [commit]
  #       additional_dependencies: [black==20.8b1]
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #     - id: seed-isort-config
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.4.2
  #   hooks:
  # #     - id: isort
  # - repo: https://github.com/detailyang/pre-commit-shell
  #   rev: 1.0.5
  #   hooks:
  #     - id: shell-lint
  #       args: [--format=json, --exclude=SC1091]